title: Learn Python via Blender
author: Anders Schneiderman
email: your-email@domain.com
description:  Description of this site

# Menu data for sitewide navigation
navigation_links:
  - name: About
    link: 'about/'
  - name: Resources
    link: 'resources/'
  - name: Notes
    link: 'notes/'
  - name: Makers All
    link: 'https://makersall.org/'

